dockerization work

diff --git a/crawl-ref/webstuff/hydrate b/crawl-ref/webstuff/hydrate
--- a/crawl-ref/webstuff/hydrate
+++ b/crawl-ref/webstuff/hydrate
@@ -1,33 +1,40 @@
 #!/bin/bash
 
+alias fail='{ return_value=1; break; }'
+
+# should be placed after any loop inside of an exception catching block
+alias maybe_break='[ $return_value == 0 ] || break'
+
 # usage: hydrate {file}
 #   will replace variables in from file with values of variables defined in current shell environment
 #   will look for a file called {file}.template and output a file called {file}
 unset hydrate
 hydrate() {
 local file from to line
-file="$1"
-from="${file}.template"
-to="$file"
-local returnValue=0
-if [ -f "$to" ]; then
-	echo "File already exists: $to"
-	return 1
-fi
-while true; do
-    if [ ! -f "$from" ]; then
-        echo "Missing file: $from"
-        fail
-    fi
-    local OIFS="$IFS"
-    IFS=$'\n'
-    while read -r line; do
-        line="${line//\"/\\\"}"
-        eval "echo \"$line\"" >>$to || fail
-    done < $from
-    break
+while [ "$1" ]; do
+  file="$1"; shift
+  from="${file}.template"
+  to="$file"
+  local returnValue=0
+  if [ -f "$to" ]; then
+          echo "File already exists: $to"
+          fail
+  fi
+
+  if [ ! -f "$from" ]; then
+      echo "Missing file: $from"
+      fail
+  fi
+  local OIFS="$IFS"
+  IFS=$'\n'
+  while read -r line; do
+      line="${line//\"/\\\"}"
+      eval "echo \"$line\"" >>$to || fail
+  done < $from
+  IFS="$OIFS"
+
+  rm $from || returnValue=1
 done
-IFS="$OIFS"
 return $returnValue
 }
 
