m

diff --git a/crawl-ref/docker/webstuff/hydrate b/crawl-ref/docker/webstuff/hydrate
--- a/crawl-ref/docker/webstuff/hydrate
+++ b/crawl-ref/docker/webstuff/hydrate
@@ -12,18 +12,18 @@ alias maybe_break='[ $return_value == 0 ] || break'
 unset hydrate
 hydrate() {
 local file from to line
+local returnValue=0
 while [ "$1" ]; do
   file="$1"; shift
   from="${file}.template"
   to="$file"
-  local returnValue=0
   if [ -f "$to" ]; then
-          echo "File already exists: $to"
-          fail
+      echo "File already exists: $to" >&2
+      fail
   fi
 
   if [ ! -f "$from" ]; then
-      echo "Missing file: $from"
+      echo "Missing file: $from" >&2
       fail
   fi
   local OIFS="$IFS"
@@ -33,12 +33,13 @@ while [ "$1" ]; do
       eval "echo \"$line\"" >>$to || fail
   done < $from
   IFS="$OIFS"
+  maybe_break
 
   chmod --reference $from $to || fail
-  rm $from || returnValue=1
+  rm $from || fail
 done
 return $returnValue
 }
 
-hydrate "$@"
+hydrate "$@" || exit 1
 
